# Generated by Django 4.0.7 on 2023-09-12 08:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('document_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_color', models.CharField(choices=[('Colored', 'Colored'), ('B&W', 'Black_and_white')], max_length=7)),
                ('number_of_copies', models.IntegerField()),
                ('pages_to_print', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Print_log',
            fields=[
                ('printlog_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('time', models.DateTimeField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.document')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('ADMIN', 'Admin'), ('USER', 'User')], max_length=50)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('contacts', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Print_Queue',
            fields=[
                ('printqueue_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.document')),
                ('printlog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.print_log')),
            ],
        ),
        migrations.AddField(
            model_name='print_log',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user'),
        ),
        migrations.CreateModel(
            name='Payment_Receipt',
            fields=[
                ('receipts_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('amount_remaining', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.document')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('notification_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=30)),
                ('time', models.DateTimeField()),
                ('printlog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.print_log')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.user'),
        ),
    ]
