# Generated by Django 4.0.7 on 2023-09-15 07:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('contacts', models.IntegerField()),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='role',
        ),
    ]
