# Generated by Django 4.0.7 on 2023-10-03 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
